include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

variables:
  CI_APT_INSTALL: 'libgomp1'
  NVIDIA_VISIBLE_DEVICES: 'all'
  NVIDIA_DRIVER_CAPABILITIES: 'compute,utility'


# CUDA versions

# other tasks

documentation:
  extends:
    - .julia:1.5
    - .documentation
  tags:
    - nvidia

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master


# benchmarks

.benchmark:
  stage: post
  interruptible: true
  tags:
    - nvidia-benchmark
  only:
    refs:
      - master
  variables:
    JULIA_LOAD_PATH: "$CI_PROJECT_DIR:$CI_PROJECT_DIR/perf::"
    CODESPEED_ENVIRONMENT: "$CI_RUNNER_DESCRIPTION"
    CODESPEED_PROJECT: "$CI_PROJECT_NAME"
    CODESPEED_BRANCH: "$CI_COMMIT_REF_NAME"
    CODESPEED_COMMIT: "$CI_COMMIT_SHA"
  script:
    - julia --project --color=yes -e 'using Pkg;
                                      Pkg.instantiate()'
    - julia --project=perf/ --color=yes -e 'using Pkg;
                                            Pkg.instantiate()'
    - julia --project=perf/ --color=yes perf/runbenchmarks.jl

benchmark:1.5:
  extends:
    - .julia:1.5
    - .benchmark
  tags:
    - nvidia-benchmark
  variables:
    CODESPEED_EXECUTABLE: "Julia 1.5"
